package main.project.movie.controller.attribute;

import main.project.movie.controller.command.Router;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public final class AttributeName {
    public static Router router = new Router();
    public static final String PAGE = "page";
    public static final String ID = "id";
    public static final String USER_PAGE = "user_page";
    public static final String EXIST_MOVIE = "exist_movie";
    public static final String MOVIE_NAME = "movieName";
    public static final String COUNTRY_NAME = "countryName";
    public static final String CREATED_YEAR = "createdYear";
    public static final String CATEGORY = "category";
    public static final String LANGUAGE = "language";
    public static final String AGE_LIMIT = "ageLimit";
    public static final String IMAGE_PATH = "imagePath";
    public static final String ADD_MASSAGE = "add_massage";
    public static final String MOVIE_CATEGORY = "movie_category";
    public static final String MOVIE_CATEGORY_LIST = "movie_category_list";
    public static final String ROLE = "role";
    public static final String USER_ID = "user_id";
    public static final String USER = "user";
    public static final String COMMENT = "comment";
    public static final String COMMENT_LIST = "comment_list";
    public static final String COMMENT_TEXT = "comment_text";
    public static final String COMMENT_ID = "comment_id";
    public static final String SUCCESS = "success";
    public static final String FAIL = "fail";
    public static final String DELETE_MESSAGE = "delete_message";
    public static final String RETURN_PAGE = "return_page";
    public static final String DELETING_MESSAGE = "deleting_message";
    public static final String UPDATE_MESSAGE = "update_message";
    public static final String ADMIN_PAGE = "admin_page";
    public static final String DESCRIPTION = "description";
    public static final String ADMINS = "admins";
    public static final String MOVIE_LIST = "movie_list";
    public static final String ADD_MESSAGE = "add_message";
    public static final String USERS = "users";
    public static final String USERID = "userid";
    public static final String EMAIL = "email";
    public static final String FIRSTNAME = "firstname";
    public static final String LASTNAME = "lastname";
    public static final String NEW_LIST = "new_list";
    public static final String BEST_LIST = "best_list";
    public static final String ADVENTURE_LIST = "adventure_list";
    public static final String SERIAL_LIST = "serial_list";
    public static final String CARTOON_LIST = "cartoon_list";
    public static final String FILM_LIST = "film_list";
    public static final String COMEDY_LIST = "comedy_list";
    public static final String USERNAME = "username";
    public static final String PASSWORD = "password";
    public static final String CURRENT_PAGE = "current_page";
    public static final String INDEX_PAGE = "/index.jsp";
    public static final String USER_ROLE = "UserRole";
    public static final String USER_STATUS = "UserStatus";
    public static final String LOGIN_MESSAGE = "login_message";
    public static final String PROFILE_BLOCKED = "profile_blocked";
    public static final String LOGIN_SUCCESS = "login_success";
    public static final String INCORRECT = "incorrect";
    public static final String RATING_INFO = "rating_info";
    public static final String RATE = "rate";
    public static final String MOVIE_ID = "id";
    public static final String NEW_PASSWORD = "new_password";
    public static final String STATUS = "status";
    public static final String CONF_PASSWORD = "confPassword";
    public static final String NOT_MATCHES_PSW = "notMatchPasswords";
    public static final String REG_USERNAME = "reg_username";
    public static final String REG_PASSWORD = "reg_password";
    public static final String RE_PASSWORD = "re_password";
    public static final String REG_MESSAGE = "reg_message";
    public static final String ADMIN_USERNAME = "AdminGeneral";
    public static final String NOT_MATCHES_PSW_REG = "not_matches_passwords";
    public static final String EXIST_LOGIN = "exist_login";
    public static final String EXIST_EMAIL = "exist_email";
    public static final String ERROR = "error";
    public static final String SENDER_EMAIL = "moxirbek021199@gmail.com";
    public static final String GOOGLE_SECURITY_PASSWORD = "tapymvhauydrxfrf";
    public static final String SENT_PASSWORD = "sent_password";
    public static final String MESSAGE = "message";
    public static final String CONFRM_PSW_SENT_TO_EMAIL = "Confirm password is sent to your email: ";
    public static final String MOVIE_INFO = "movie_info";
    public static final String RESET_SUCCESS = "resetSuccess";
    public static final String RESET_FAILED = "resetFailed";
    public static final String CONFIRM_PASSWORD = "confirm_password";
    public static final String COMMAND = "command";
    public static final String ERROR_MSG = "error_msg";

    private AttributeName(){}
}
